name: GHA_DEMO
on:
  push:
    branches:
      - '*'
  workflow_dispatch:

jobs:
    random_word:
        runs-on: ubuntu-latest
        steps:
            - name: Create Random Word
              id: random_word
              uses: shyjuezy/gha_custom_action_demo@v1
              with:
                  word_length: 10
            - name: Print output
              run: |
                  echo "The output is ${{ steps.random_word.outputs.random_word }}"
