name: test main
env:
  python_version: 3.9

on:
  push:
    branches:
      - '*'
  workflow_dispatch:


jobs:
  test:
    runs-on: ubuntu-latest
    outputs:
      python_version: ${{ steps.set-python-version.outputs.python_version }}
    steps:
    - name: Print env variables
      id: set-python-version
      run: |
        echo "name is ${{ env.name }}"
        echo "version is ${{ env.python_version }}"
        echo "Testing - $python_version"
        echo "GITHUB_REF is $GITHUB_REF"
        echo "ENV is ${{ toJSON(env) }}"
        echo "python_version=${{ env.python_version }}" >> $GITHUB_OUTPUT

#  random_word:
#    needs: test
#    uses: ./.github/workflows/random_word.yml
  call_test:
    runs-on: ubuntu-latest
    steps:
      - name: Call test
        id: call-test
        uses: shyjuezy/gh-random-word@v1
        with:
          word_length: 10
      - name: Print output
        run: |
          echo "The output is ${{ steps.call-test.outputs.random_word }}"
